import type { IonItem, CoexistenceConflict } from './types'

export const ION_DATA: IonItem[] = [
  // ── 阳离子 (Cations) ──
  {
    id: 'Fe3+',
    name: '铁离子 (Fe³⁺)',
    formula: 'Fe^{3+}',
    charge: 3,
    type: 'cation',
    colorInSolution: '黄色 / 棕黄色',
    colorRgb: 'rgba(217, 119, 6, 0.8)',
    testReagent: 'KSCN 溶液 或 NaOH 溶液',
    testPhenomenon: '滴加 KSCN 显血红色；滴加 NaOH 生成红褐色沉淀',
    testEquation: 'Fe^{3+} + 3SCN^- \\rightleftharpoons Fe(SCN)_3 (血红色)',
    interference: 'Fe²⁺ 不与 KSCN 反应；若含大量还原剂可能影响显色',
    standardProcedure: '取少量待测液于试管中，滴加几滴 KSCN 溶液，若溶液立即变为血红色，则证明原溶液中含有 Fe³⁺。',
    examImportance: 'ultra',
  },
  {
    id: 'Fe2+',
    name: '亚铁离子 (Fe²⁺)',
    formula: 'Fe^{2+}',
    charge: 2,
    type: 'cation',
    colorInSolution: '浅绿色',
    colorRgb: 'rgba(16, 185, 129, 0.7)',
    testReagent: 'KSCN 溶液 + 氯水 (或 H₂O₂)',
    testPhenomenon: '先加 KSCN 溶液无明显现象 (不变红)，再滴加氯水 (或 H₂O₂) 溶液立即变为血红色',
    testEquation: '2Fe^{2+} + Cl_2 = 2Fe^{3+} + 2Cl^- ; Fe^{3+} + 3SCN^- = Fe(SCN)_3',
    interference: '原溶液不能先有 Fe³⁺；必须按“先加 KSCN 不变红，后加氧化剂变红”的标准顺序',
    standardProcedure: '取少量待测液于试管中，先滴加 2 滴 KSCN 溶液，无明显变化；再滴加新制氯水，溶液立即变为血红色，证明含 Fe²⁺。',
    examImportance: 'ultra',
  },
  {
    id: 'Cu2+',
    name: '铜离子 (Cu²⁺)',
    formula: 'Cu^{2+}',
    charge: 2,
    type: 'cation',
    colorInSolution: '蓝色',
    colorRgb: 'rgba(37, 99, 235, 0.8)',
    testReagent: 'NaOH 溶液 或 氨水',
    testPhenomenon: '加 NaOH 生成蓝色絮状沉淀 Cu(OH)₂；加过量氨水沉淀溶解生成深蓝色络离子 [Cu(NH₃)₄]²⁺',
    testEquation: 'Cu^{2+} + 2OH^- = Cu(OH)_2\\downarrow ; Cu(OH)_2 + 4NH_3 = [Cu(NH_3)_4]^{2+} + 2OH^-',
    interference: 'Fe³⁺、Fe²⁺ 沉淀颜色可能掩盖蓝色沉淀',
    standardProcedure: '取待测液加入 NaOH 溶液生成蓝色沉淀，继续滴加氨水沉淀溶解并变为深蓝色透明溶液。',
    examImportance: 'high',
  },
  {
    id: 'Al3+',
    name: '铝离子 (Al³⁺)',
    formula: 'Al^{3+}',
    charge: 3,
    type: 'cation',
    colorInSolution: '无色',
    colorRgb: 'rgba(226, 232, 240, 0.6)',
    testReagent: 'NaOH 溶液',
    testPhenomenon: '滴加 NaOH 溶液先生成白色胶状沉淀，NaOH 过量后白色沉淀完全溶解',
    testEquation: 'Al^{3+} + 3OH^- = Al(OH)_3\\downarrow ; Al(OH)_3 + OH^- = [Al(OH)_4]^- (或 AlO_2^- + 2H_2O)',
    interference: 'Mg²⁺、Ca²⁺ 生成沉淀但过量 NaOH 不溶解；可用过量 NaOH 区分 Al³⁺ 与 Mg²⁺',
    standardProcedure: '向待测液中逐滴加入 NaOH 溶液，先产生白色胶状沉淀，继续滴加 NaOH 沉淀全部溶解，证明含 Al³⁺。',
    examImportance: 'ultra',
  },
  {
    id: 'NH4+',
    name: '铵根离子 (NH₄⁺)',
    formula: 'NH_4^+',
    charge: 1,
    type: 'cation',
    colorInSolution: '无色',
    colorRgb: 'rgba(241, 245, 249, 0.6)',
    testReagent: '浓 NaOH 溶液 + 加热 + 湿润红色石蕊试纸',
    testPhenomenon: '加热产生有刺激性气味的气体，能使湿润的红色石蕊试纸变蓝',
    testEquation: 'NH_4^+ + OH^- \\xrightarrow{\\Delta} NH_3\\uparrow + H_2O',
    interference: '试纸必须“湿润”，且不能接触试管壁，防止附着的 NaOH 液滴造成假阳性',
    standardProcedure: '取少许样品于试管中，加入浓 NaOH 溶液并微热，将湿润的红色石蕊试纸置于试管口附近，若试纸变蓝，则证明含 NH₄⁺。',
    examImportance: 'ultra',
  },
  {
    id: 'Ba2+',
    name: '钡离子 (Ba²⁺)',
    formula: 'Ba^{2+}',
    charge: 2,
    type: 'cation',
    colorInSolution: '无色',
    colorRgb: 'rgba(248, 250, 252, 0.6)',
    testReagent: '稀硫酸 (或 Na₂SO₄ 溶液) + 稀硝酸',
    testPhenomenon: '生成白色沉淀，且沉淀不溶于稀硝酸；焰色试验呈黄绿色',
    testEquation: 'Ba^{2+} + SO_4^{2-} = BaSO_4\\downarrow (不溶于稀硝酸)',
    interference: 'Ag⁺ 遇硫酸也会生成微溶物；Pb²⁺ 会生成沉淀；需配合焰色试验或稀盐酸排除',
    standardProcedure: '取待测液滴加稀硫酸生成白色沉淀，加稀硝酸沉淀不溶解，焰色试验呈黄绿色。',
    examImportance: 'high',
  },
  {
    id: 'Ag+',
    name: '银离子 (Ag⁺)',
    formula: 'Ag^+',
    charge: 1,
    type: 'cation',
    colorInSolution: '无色',
    colorRgb: 'rgba(241, 245, 249, 0.6)',
    testReagent: '稀盐酸 (或 NaCl 溶液) + 稀硝酸 + 氨水',
    testPhenomenon: '生成白色沉淀，沉淀不溶于稀硝酸，但可溶于过量氨水',
    testEquation: 'Ag^+ + Cl^- = AgCl\\downarrow ; AgCl + 2NH_3 = [Ag(NH_3)_2]^+ + Cl^-',
    interference: 'Pb²⁺ 遇盐酸也生成白色沉淀 (PbCl₂ 溶于热水)',
    standardProcedure: '取待测液加入稀盐酸生成白色沉淀，加稀硝酸不溶，滴加氨水沉淀溶解生成无色银氨溶液。',
    examImportance: 'high',
  },
  {
    id: 'Mg2+',
    name: '镁离子 (Mg²⁺)',
    formula: 'Mg^{2+}',
    charge: 2,
    type: 'cation',
    colorInSolution: '无色',
    colorRgb: 'rgba(248, 250, 252, 0.6)',
    testReagent: 'NaOH 溶液 (过量)',
    testPhenomenon: '生成白色沉淀，过量 NaOH 溶液中沉淀不溶解',
    testEquation: 'Mg^{2+} + 2OH^- = Mg(OH)_2\\downarrow (白色沉淀，不溶于强碱)',
    interference: '与 Al³⁺ 区别：Al(OH)₃ 溶于过量 NaOH，而 Mg(OH)₂ 不溶',
    standardProcedure: '向待测液中滴加过量 NaOH 溶液，生成白色沉淀且沉淀不溶解，证明含有 Mg²⁺。',
    examImportance: 'high',
  },

  // ── 阴离子 (Anions) ──
  {
    id: 'SO42-',
    name: '硫酸根离子 (SO₄²⁻)',
    formula: 'SO_4^{2-}',
    charge: -2,
    type: 'anion',
    colorInSolution: '无色',
    colorRgb: 'rgba(248, 250, 252, 0.6)',
    testReagent: '稀盐酸 + BaCl₂ 溶液',
    testPhenomenon: '先加稀盐酸无沉淀/气体，再加 BaCl₂ 溶液产生白色沉淀',
    testEquation: 'Ba^{2+} + SO_4^{2-} = BaSO_4\\downarrow (白色沉淀，不溶于酸)',
    interference: '必须先加稀盐酸排除 Ag⁺ (生成 AgCl 沉淀)、SO₃²⁻/CO₃²⁻ (生成 BaSO₃/BaCO₃ 沉淀) 的干扰！',
    standardProcedure: '取少量待测液于试管中，先加足量稀盐酸酸化无明显现象，再滴加 BaCl₂ 溶液，若产生白色沉淀，证明含 SO₄²⁻。',
    examImportance: 'ultra',
  },
  {
    id: 'Cl-',
    name: '氯离子 (Cl⁻)',
    formula: 'Cl^-',
    charge: -1,
    type: 'anion',
    colorInSolution: '无色',
    colorRgb: 'rgba(248, 250, 252, 0.6)',
    testReagent: '稀硝酸 + AgNO₃ 溶液',
    testPhenomenon: '生成白色沉淀，沉淀不溶于稀硝酸',
    testEquation: 'Ag^+ + Cl^- = AgCl\\downarrow (白色沉淀)',
    interference: 'CO₃²⁻、SO₄²⁻ 干扰：必须先加稀硝酸酸化排除 CO₃²⁻ 等杂质干扰',
    standardProcedure: '取少许待测液于试管中，加入稀硝酸酸化，再滴加 AgNO₃ 溶液，若产生白色沉淀，证明含 Cl⁻。',
    examImportance: 'ultra',
  },
  {
    id: 'Br-',
    name: '溴离子 (Br⁻)',
    formula: 'Br^-',
    charge: -1,
    type: 'anion',
    colorInSolution: '无色',
    colorRgb: 'rgba(248, 250, 252, 0.6)',
    testReagent: 'AgNO₃ 溶液 + 稀硝酸 (或 氯水 + CCl₄ 萃取)',
    testPhenomenon: '加 AgNO₃ 生成淡黄色沉淀 (AgBr)；加氯水振荡后加 CCl₄，下层呈橙红色',
    testEquation: '2Br^- + Cl_2 = Br_2 + 2Cl^- (Br_2 \\text{ 在 } CCl_4 \\text{ 中呈橙红色})',
    interference: 'I⁻ 干扰：I₂ 在 CCl₄ 中呈紫红色，AgI 为黄色沉淀',
    standardProcedure: '取待测液加入氯水和少量 CCl₄ 振荡静置，下层有机层呈橙红色，证明含 Br⁻。',
    examImportance: 'high',
  },
  {
    id: 'I-',
    name: '碘离子 (I⁻)',
    formula: 'I^-',
    charge: -1,
    type: 'anion',
    colorInSolution: '无色',
    colorRgb: 'rgba(248, 250, 252, 0.6)',
    testReagent: '氯水 (或 FeCl₃ / H₂O₂) + 淀粉溶液 (或 CCl₄)',
    testPhenomenon: '滴加氧化剂与淀粉溶液，溶液立即变为深蓝色；或加入 CCl₄ 萃取下层呈紫红色',
    testEquation: '2I^- + 2Fe^{3+} = 2Fe^{2+} + I_2 ; I_2 + \\text{淀粉} \\rightarrow \\text{深蓝色络合物}',
    interference: '还原性物质可能竞争消耗氧化剂；淀粉指示极灵敏',
    standardProcedure: '取少量待测液滴加淀粉溶液，再滴入几滴新制氯水（或 FeCl₃ 溶液），溶液变蓝，证明含 I⁻。',
    examImportance: 'ultra',
  },
  {
    id: 'CO32-',
    name: '碳酸根离子 (CO₃²⁻)',
    formula: 'CO_3^{2-}',
    charge: -2,
    type: 'anion',
    colorInSolution: '无色',
    colorRgb: 'rgba(248, 250, 252, 0.6)',
    testReagent: 'BaCl₂ 溶液 (或 CaCl₂) + 稀盐酸 + 澄清石灰水',
    testPhenomenon: '加 BaCl₂ 生成白色沉淀；沉淀溶于稀盐酸并产生无色无味能使澄清石灰水变浑浊的气体',
    testEquation: 'Ba^{2+} + CO_3^{2-} = BaCO_3\\downarrow ; BaCO_3 + 2H^+ = Ba^{2+} + CO_2\\uparrow + H_2O',
    interference: 'HCO₃⁻ 不与 BaCl₂/CaCl₂ 生成沉淀，以此严格区分 CO₃²⁻ 与 HCO₃⁻；SO₃²⁻ 产生的 SO₂ 有刺激性气味且使品红褪色',
    standardProcedure: '向待测液中加入 BaCl₂ 溶液生成白色沉淀，滤出沉淀加稀盐酸产生气体，通入澄清石灰水变浑浊，证明含 CO₃²⁻。',
    examImportance: 'ultra',
  },
  {
    id: 'SO32-',
    name: '亚硫酸根离子 (SO₃²⁻)',
    formula: 'SO_3^{2-}',
    charge: -2,
    type: 'anion',
    colorInSolution: '无色',
    colorRgb: 'rgba(248, 250, 252, 0.6)',
    testReagent: '稀盐酸 + 品红溶液 (或 BaCl₂ 溶液)',
    testPhenomenon: '加稀盐酸产生有刺激性气味的气体，该气体能使品红溶液褪色，加热后恢复红色',
    testEquation: 'SO_3^{2-} + 2H^+ = SO_2\\uparrow + H_2O ; SO_2 + \\text{品红} \\rightleftharpoons \\text{无色物质}',
    interference: 'CO₃²⁻ 产生的 CO₂ 无刺激性气味且不能使品红褪色',
    standardProcedure: '取待测液加入稀盐酸，产生的气体通入品红溶液中使其褪色，加热品红溶液又恢复红色，证明含 SO₃²⁻。',
    examImportance: 'ultra',
  },
  {
    id: 'S2-',
    name: '硫离子 (S²⁻)',
    formula: 'S^{2-}',
    charge: -2,
    type: 'anion',
    colorInSolution: '无色',
    colorRgb: 'rgba(248, 250, 252, 0.6)',
    testReagent: 'CuSO₄ 溶液 (或 稀盐酸 + 湿润醋酸铅试纸)',
    testPhenomenon: '加入 CuSO₄ 产生黑色沉淀 CuS (不溶于稀盐酸)；加酸产生臭鸡蛋气味 H₂S 使醋酸铅试纸变黑',
    testEquation: 'Cu^{2+} + S^{2-} = CuS\\downarrow (黑色沉淀) ; Pb^{2+} + H_2S = PbS\\downarrow + 2H^+',
    interference: '易被空气中氧气氧化为单质 S 沉淀',
    standardProcedure: '取待测液滴加 CuSO₄ 溶液产生黑色不溶于酸的沉淀，证明含 S²⁻。',
    examImportance: 'high',
  },
  {
    id: 'NO3-',
    name: '硝酸根离子 (NO₃⁻/H⁺)',
    formula: 'NO_3^-',
    charge: -1,
    type: 'anion',
    colorInSolution: '无色',
    colorRgb: 'rgba(248, 250, 252, 0.6)',
    testReagent: '铜片 + 浓硫酸 (或 棕色环实验)',
    testPhenomenon: '中性无明显氧化性，加酸后与铜片反应产生红棕色 NO₂ (或无色 NO 在管口变红棕色) 与蓝色溶液',
    testEquation: '3Cu + 8H^+ + 2NO_3^- = 3Cu^{2+} + 2NO\\uparrow + 4H_2O ; 2NO + O_2 = 2NO_2 (红棕色)',
    interference: '必须在酸性条件 (H⁺ 存在) 下才表现强氧化性',
    standardProcedure: '向待测液中加入铜片并滴加浓硫酸微热，试管口出现红棕色气体且溶液变蓝，证明含 NO₃⁻。',
    examImportance: 'high',
  },
]

export const COEXISTENCE_CONFLICTS: CoexistenceConflict[] = [
  // 1. 生成沉淀 (Precipitates)
  {
    id: 'c-ba-so4',
    ionA: 'Ba2+',
    ionB: 'SO42-',
    type: 'precipitate',
    typeLabel: '生成不溶性硫酸盐沉淀',
    reason: 'Ba²⁺ 与 SO₄²⁻ 极易结合生成难溶于水和强酸的白色 BaSO₄ 沉淀 (Ksp = 1.1 × 10⁻¹⁰)',
    equation: 'Ba^{2+} + SO_4^{2-} = BaSO_4\\downarrow',
  },
  {
    id: 'c-ag-cl',
    ionA: 'Ag+',
    ionB: 'Cl-',
    type: 'precipitate',
    typeLabel: '生成难溶氯化物沉淀',
    reason: 'Ag⁺ 与 Cl⁻ 结合生成不溶于稀硝酸的白色 AgCl 沉淀 (Ksp = 1.8 × 10⁻¹⁰)',
    equation: 'Ag^+ + Cl^- = AgCl\\downarrow',
  },
  {
    id: 'c-ag-so4',
    ionA: 'Ag+',
    ionB: 'SO42-',
    type: 'precipitate',
    typeLabel: '生成微溶沉淀',
    reason: 'Ag⁺ 与 SO₄²⁻ 结合生成微溶的 Ag₂SO₄，高浓度时产生沉淀',
    equation: '2Ag^+ + SO_4^{2-} = Ag_2SO_4\\downarrow',
  },
  {
    id: 'c-fe3-oh',
    ionA: 'Fe3+',
    ionB: 'CO32-',
    type: 'double-hydrolysis',
    typeLabel: '剧烈双水解生成沉淀与气体',
    reason: 'Fe³⁺ 水解显强酸性，CO₃²⁻ 水解显强碱性，两者混合互相促进水解彻底，生成 Fe(OH)₃ 沉淀和 CO₂ 气体',
    equation: '2Fe^{3+} + 3CO_3^{2-} + 3H_2O = 2Fe(OH)_3\\downarrow + 3CO_2\\uparrow',
  },
  {
    id: 'c-al3-co3',
    ionA: 'Al3+',
    ionB: 'CO32-',
    type: 'double-hydrolysis',
    typeLabel: '剧烈双水解生成沉淀与气体',
    reason: 'Al³⁺ 与 CO₃²⁻ (或 HCO₃⁻) 发生彻底双水解反应，生成白色 Al(OH)₃ 沉淀与 CO₂ 气体，不能大量共存',
    equation: '2Al^{3+} + 3CO_3^{2-} + 3H_2O = 2Al(OH)_3\\downarrow + 3CO_2\\uparrow',
  },
  {
    id: 'c-al3-hco3',
    ionA: 'Al3+',
    ionB: 'HCO3-',
    type: 'double-hydrolysis',
    typeLabel: '剧烈双水解生成沉淀与气体 (泡沫灭火器原理)',
    reason: 'Al³⁺ 与 HCO₃⁻ 彻底双水解，生成 Al(OH)₃ 沉淀和 CO₂ 气体',
    equation: 'Al^{3+} + 3HCO_3^- = Al(OH)_3\\downarrow + 3CO_2\\uparrow',
  },
  {
    id: 'c-al3-s2',
    ionA: 'Al3+',
    ionB: 'S2-',
    type: 'double-hydrolysis',
    typeLabel: '彻底双水解生成沉淀与臭鸡蛋气体',
    reason: 'Al³⁺ 与 S²⁻ 在水溶液中无法生成 Al₂S₃，而是彻底双水解生成 Al(OH)₃ 沉淀和 H₂S 气体',
    equation: '2Al^{3+} + 3S^{2-} + 6H_2O = 2Al(OH)_3\\downarrow + 3H_2S\\uparrow',
  },
  // 2. 氧化还原互斥 (Redox)
  {
    id: 'c-fe3-i',
    ionA: 'Fe3+',
    ionB: 'I-',
    type: 'redox',
    typeLabel: '氧化还原互斥反应',
    reason: 'Fe³⁺ 具有较强氧化性，I⁻ 具有强还原性，两者发生自发氧化还原生成 Fe²⁺ 和 I₂ 单质',
    equation: '2Fe^{3+} + 2I^- = 2Fe^{2+} + I_2',
  },
  {
    id: 'c-fe3-s2',
    ionA: 'Fe3+',
    ionB: 'S2-',
    type: 'redox',
    typeLabel: '氧化还原互斥反应',
    reason: 'Fe³⁺ 氧化 S²⁻ 生成单质 S 黄色沉淀和 Fe²⁺ (过量 S²⁻ 生成 FeS 黑色沉淀)',
    equation: '2Fe^{3+} + S^{2-} = 2Fe^{2+} + S\\downarrow',
  },
  {
    id: 'c-fe3-so3',
    ionA: 'Fe3+',
    ionB: 'SO32-',
    type: 'redox',
    typeLabel: '氧化还原互斥反应',
    reason: 'Fe³⁺ 能将强还原性的 SO₃²⁻ 氧化为 SO₄²⁻，自身被还原为 Fe²⁺',
    equation: '2Fe^{3+} + SO_3^{2-} + H_2O = 2Fe^{2+} + SO_4^{2-} + 2H^+',
  },
  {
    id: 'c-cu2-s2',
    ionA: 'Cu2+',
    ionB: 'S2-',
    type: 'precipitate',
    typeLabel: '生成极难溶沉淀',
    reason: 'Cu²⁺ 与 S²⁻ 结合生成极难溶的黑色 CuS 沉淀 (Ksp = 6.3 × 10⁻³⁶，不溶于非氧化性强酸)',
    equation: 'Cu^{2+} + S^{2-} = CuS\\downarrow',
  },
  {
    id: 'c-fe2-no3',
    ionA: 'Fe2+',
    ionB: 'NO3-',
    type: 'redox',
    typeLabel: '酸性条件下氧化还原互斥',
    reason: '在中性溶液中可共存，但在酸性溶液 (含 H⁺) 中，NO₃⁻ 具有强氧化性，迅速将 Fe²⁺ 氧化为 Fe³⁺',
    equation: '3Fe^{2+} + NO_3^- + 4H^+ = 3Fe^{3+} + NO\\uparrow + 2H_2O',
  },
  {
    id: 'c-nh4-co3-base',
    ionA: 'NH4+',
    ionB: 'OH-',
    type: 'weak-electrolyte',
    typeLabel: '生成弱电解质或挥发性气体',
    reason: 'NH₄⁺ 与 OH⁻ 结合生成弱电解质一水合氨 NH₃·H₂O，加热逸出 NH₃ 气体',
    equation: 'NH_4^+ + OH^- \\rightleftharpoons NH_3\\cdot H_2O \\xrightarrow{\\Delta} NH_3\\uparrow + H_2O',
  },
]
