import type { FlashCard } from './types'

export const FLASH_CARDS: FlashCard[] = [
  {
    id: 'card-1',
    category: 'bleaching-redox',
    categoryLabel: '漂白与氧化',
    title: 'SO₂ 与 Cl₂ 漂白品红后加热复红对比',
    question: '将 SO₂ 和 Cl₂ 分别通入品红溶液中使其褪色，随后分别加热褪色后的溶液，现象有何不同？',
    optionA: '通入 SO₂ 的溶液加热恢复红色；通入 Cl₂ 的溶液加热不恢复红色',
    optionB: '两者加热后均能完全恢复红色',
    correctOption: 'A',
    explanation: 'SO₂ 漂白属于结合型（与色素生成不稳定无色物质，加热解离复红）；Cl₂ 漂白是因为生成强氧化性的 HClO 破坏色素结构，不可逆且加热不复红。',
    chemicalEquations: [
      'SO_2 + \\text{品红} \\rightleftharpoons \\text{无色不稳定产物} (结合型漂白，加热解离复红)',
      'Cl_2 + H_2O = HCl + HClO (氧化型漂白破坏色素，加热不复红)',
    ],
    warningTip: '高考避坑红线：区分结合型漂白（SO₂）、氧化型漂白（Cl₂/HClO/O₃/Na₂O₂）与吸附型漂白（活性炭）。仅 SO₂ 漂白加热可复红！',
    examPoint: 'SO₂ 漂白的物理化学可逆性与 Cl₂ 强氧化性不可逆漂白的机理辨析',
    relatedKnowledgeIds: ['sulfur', 'chlorine'],
    sceneType: 'bleach-heating',
  },
  {
    id: 'card-2',
    category: 'bleaching-redox',
    categoryLabel: '漂白与氧化',
    title: '等物质的量 SO₂ 与 Cl₂ 混合通入品红溶液',
    question: '将等物质的量的 SO₂ 与 Cl₂ 混合后通入品红溶液中，溶液是否褪色？',
    optionA: '褪色更迅速，漂白效果叠加增强',
    optionB: '不褪色，两者在水溶液中发生氧化还原反应失去漂白性',
    correctOption: 'B',
    explanation: '等摩尔的 SO₂ 与 Cl₂ 混合通入水中，发生反应 SO₂ + Cl₂ + 2H₂O = H₂SO₄ + 2HCl，生成的硫酸与盐酸无漂白性，故品红溶液不褪色。',
    chemicalEquations: [
      'SO_2 + Cl_2 + 2H_2O = H_2SO_4 + 2HCl (等摩尔氧化还原，失去漂白性)',
    ],
    warningTip: '高考避坑红线：切忌直觉以为“两种漂白剂混合效果加倍”！氧化性与还原性气体混合优先发生氧化还原反应。',
    examPoint: '氧化还原反应竞争优先于性质表现及代数等当量判断',
    relatedKnowledgeIds: ['sulfur', 'chlorine'],
    sceneType: 'bleach-heating',
  },
  {
    id: 'card-3',
    category: 'bleaching-redox',
    categoryLabel: '漂白与氧化',
    title: 'SO₂ 与 CO₂ 使澄清石灰水与高锰酸钾褪色对比',
    question: 'SO₂ 和 CO₂ 通入澄清石灰水均能变浑浊，如何用化学试剂快速鉴别 SO₂ 与 CO₂？',
    optionA: '通入酸性 KMnO₄ 溶液，能使其紫红色褪色的是 SO₂，不能的是 CO₂',
    optionB: '通入澄清石灰水无现象的是 SO₂',
    correctOption: 'A',
    explanation: 'SO₂ 具有强还原性，能被酸性 KMnO₄ 或溴水氧化使其褪色；而 CO₂ 无还原性不反应。通入澄清石灰水两者均生成不溶性钙盐沉淀。',
    chemicalEquations: [
      '5SO_2 + 2MnO_4^- + 2H_2O = 5SO_4^{2-} + 2Mn^{2+} + 4H^+ (SO₂表现强还原性)',
      'SO_2 + Ca(OH)_2 = CaSO_3\\downarrow + H_2O (生成沉淀变浑浊)',
    ],
    warningTip: '高考避坑红线：SO₂ 使酸性 KMnO₄ 褪色是还原性（发生了氧化还原反应），而不是漂白性！',
    examPoint: 'SO₂ 的还原性与漂白性的严格区分，以及 CO₂/SO₂ 气体检验顺序链',
    relatedKnowledgeIds: ['sulfur', 'carbon-dioxide'],
    sceneType: 'bleach-heating',
  },
  {
    id: 'card-4',
    category: 'passivation-acid',
    categoryLabel: '钝化与强酸',
    title: '常温下铁/铝在浓硫酸中的钝化现象与本质',
    question: '常温下将铁片投入浓硫酸中无气泡产生，这是因为铁与浓硫酸不发生化学反应吗？',
    optionA: '错，常温发生钝化（表面氧化为致密薄膜），钝化属于化学变化',
    optionB: '对，常温下铁金属性弱无法与浓硫酸反应，加热才能反应',
    correctOption: 'A',
    explanation: '常温下浓硫酸、浓硝酸具有强氧化性，使 Fe、Al 表面立即氧化生成一层致密的钝化氧化膜（主要为 Fe₂O₃、Al₂O₃ 等），阻止反应继续进行。钝化是化学变化！',
    chemicalEquations: [
      '2Fe + 6H_2SO_4(\\text{浓}) \\xrightarrow{\\text{常温}} \\text{致密钝化膜} (钝化阻断反应)',
      '2Fe + 6H_2SO_4(\\text{浓}) \\xrightarrow{\\Delta} Fe_2(SO_4)_3 + 3SO_2\\uparrow + 6H_2O (加热破膜剧烈反应)',
    ],
    warningTip: '高考避坑红线：钝化绝不是“不反应”，而是“剧烈反应生成致密膜后阻断”！可以用铝瓶装运常温浓硝酸。',
    examPoint: '钝化概念解析、物理变化与化学变化界定及加热破膜反应',
    relatedKnowledgeIds: ['iron', 'aluminum', 'sulfur'],
    sceneType: 'passivation-heat',
  },
  {
    id: 'card-5',
    category: 'passivation-acid',
    categoryLabel: '钝化与强酸',
    title: '铜与浓硝酸 vs 稀硝酸反应产物与气体颜色对比',
    question: '铜分别与浓硝酸和稀硝酸反应，产生的气体与溶液颜色有何差异？',
    optionA: '浓硝酸产生红棕色 NO₂ 气体；稀硝酸产生无色 NO 气体（遇空气变红棕色）',
    optionB: '浓硝酸产生无色 NO 气体；稀硝酸产生红棕色 NO₂ 气体',
    correctOption: 'A',
    explanation: 'Cu + 4HNO₃(浓) = Cu(NO₃)₂ + 2NO₂↑ + 2H₂O (红棕色)；3Cu + 8HNO₃(稀) = 3Cu(NO₃)₂ + 2NO↑ + 4H₂O (无色，在空气中被 O₂ 氧化为 NO₂)。浓硝酸反应更剧烈。',
    chemicalEquations: [
      'Cu + 4HNO_3(\\text{浓}) = Cu(NO_3)_2 + 2NO_2\\uparrow + 2H_2O (红棕色气体)',
      '3Cu + 8HNO_3(\\text{稀}) = 3Cu(NO_3)_2 + 2NO\\uparrow + 4H_2O (无色气体)',
      '2NO + O_2 = 2NO_2 (无色变红棕色)',
    ],
    warningTip: '高考避坑红线：稀硝酸还原产物为 NO，浓硝酸还原产物为 NO₂。硝酸越稀，氮元素得电子后价态降得越低（如可降至 NH₄⁺）。',
    examPoint: '浓稀硝酸氧化性强弱与电子转移还原产物多样性',
    relatedKnowledgeIds: ['copper', 'nitrogen'],
    sceneType: 'passivation-heat',
  },
  {
    id: 'card-6',
    category: 'equilibrium-color',
    categoryLabel: '平衡与加压变色',
    title: 'NO₂ 与 N₂O₄ 平衡体系压缩体积加压变色探究',
    question: '将盛有 NO₂ 和 N₂O₄ 混合气体的注射器活塞迅速向内推（压缩体积），气体颜色如何变化？',
    optionA: '先变深后变浅，最终颜色仍比压缩前深',
    optionB: '持续变浅，因为平衡向生成无色 N₂O₄ 方向移动',
    correctOption: 'A',
    explanation: '压缩瞬间体积缩小，c(NO₂) 增大，颜色瞬间变深；随后平衡向气体分子数减小的正反应方向移动，c(NO₂) 减小，颜色变浅；但根据勒夏特列原理，移动不能抵消改变，新平衡 c(NO₂) 仍大于原平衡，故最终颜色比原平衡深！',
    chemicalEquations: [
      '2NO_2(g) \\rightleftharpoons N_2O_4(g) \\quad \\Delta H < 0 (加压平衡右移，新平衡浓度仍增)',
    ],
    warningTip: '高考避坑红线：平衡移动只能“减弱”改变，绝对不能“抵消”或“反转”改变！最终浓度必然高于初始状态。',
    examPoint: '勒夏特列原理深度定量理解与加压变色动态时序曲线',
    relatedKnowledgeIds: ['chemical-equilibrium', 'nitrogen'],
    sceneType: 'gas-compress',
  },
  {
    id: 'card-7',
    category: 'equilibrium-color',
    categoryLabel: '平衡与加压变色',
    title: 'FeCl₃ 与 KSCN 平衡体系中加入固体 KSCN 颜色变化',
    question: '在已达平衡的 Fe³⁺ + 3SCN⁻ ⇌ Fe(SCN)₃ 溶液中，加入少量固体 KSCN，溶液颜色如何变化？',
    optionA: '红色加深，因为增大了反应物 c(SCN⁻)，平衡正向移动',
    optionB: '颜色不变，因为固体不影响溶液中的离子平衡',
    correctOption: 'A',
    explanation: 'KSCN 易溶于水，加入固体 KSCN 溶于溶液中显著增大 c(SCN⁻)，平衡正向移动，生成更多血红色的配离子 Fe(SCN)₃，溶液红色加深。注意 KSCN 不是纯难溶沉淀！',
    chemicalEquations: [
      'Fe^{3+} + 3SCN^- \\rightleftharpoons Fe(SCN)_3 (生成血红色络合物)',
    ],
    warningTip: '高考避坑红线：易溶盐固体溶于水会急剧改变离子浓度！只有加入不溶性纯固体或水（溶剂）时才不改变浓度。',
    examPoint: '络合平衡移动与易溶固体投入对均相溶液离子浓度的冲击',
    relatedKnowledgeIds: ['chemical-equilibrium', 'iron'],
    sceneType: 'fe-kscn-equilibrium',
  },
  {
    id: 'card-8',
    category: 'inorganic-facts',
    categoryLabel: '无机常识与微粒',
    title: '金属钠投入 CuSO₄ 溶液反应本质与现象',
    question: '将一小块金属钠投入 CuSO₄ 溶液中，是否能置换出红色的金属铜单质？',
    optionA: '不能，钠先与水剧烈反应生成 NaOH 和 H₂，随后 NaOH 与 CuSO₄ 反应生成蓝色沉淀 Cu(OH)₂',
    optionB: '能，钠的金属性极强，先置换出单质铜',
    correctOption: 'A',
    explanation: '钠在水溶液中不能置换出金属单质！钠与水反应极其迅速（2Na + 2H₂O = 2NaOH + H₂↑），生成的 NaOH 接着与 CuSO₄ 发生复分解反应：2NaOH + CuSO₄ = Cu(OH)₂↓ + Na₂SO₄。现象为：浮、熔、游、响，并有蓝色沉淀生成。',
    chemicalEquations: [
      '2Na + 2H_2O = 2NaOH + H_2\\uparrow (优先与水剧烈反应)',
      '2NaOH + CuSO_4 = Cu(OH)_2\\downarrow + Na_2SO_4 (蓝色絮状沉淀)',
    ],
    warningTip: '高考避坑红线：活泼金属（Na、K、Ca）投入盐溶液，绝不能置换出盐中金属，必然是优先与水反应！只有在熔融状态下才能置换钛/钽等。',
    examPoint: '极活泼金属水溶液反应竞争动力学优先权与实验观察五字决',
    relatedKnowledgeIds: ['sodium', 'copper'],
    sceneType: 'na-water-cuso4',
  },
  {
    id: 'card-9',
    category: 'inorganic-facts',
    categoryLabel: '无机常识与微粒',
    title: 'Na₂O₂ 与 CO₂/H₂O 反应电子转移与固体重增规律',
    question: '2 mol Na₂O₂ 与足量 CO₂ 充分反应时，转移的电子数目是多少？固体质量增加多少？',
    optionA: '转移 2 mol 电子；固体增重相当于 2 mol CO 的质量',
    optionB: '转移 4 mol 电子；固体增重相当于 2 mol CO₂ 的质量',
    correctOption: 'A',
    explanation: '2Na₂O₂ + 2CO₂ = 2Na₂CO₃ + O₂ 中，过氧根中的 -1 价氧发生歧化反应（一半升高到 0 价，一半降低到 -2 价），每消耗 1 mol Na₂O₂ 转移 1 mol 电子；固体增重 Δm = m(2Na₂CO₃) - m(2Na₂O₂) = 2M(CO)。',
    chemicalEquations: [
      '2Na_2O_2 + 2CO_2 = 2Na_2CO_3 + O_2 (1mol Na₂O₂ 转移 1mol e⁻)',
      '2Na_2O_2 + 2H_2O = 4NaOH + O_2\\uparrow (增重 Δm 等同于 CO 或 H₂)',
    ],
    warningTip: '高考避坑红线：Na₂O₂ 无论与 CO₂ 还是 H₂O 反应，自身既作氧化剂又作还原剂，转移电子数与生成 O₂ 摩尔比恒为 2:1！',
    examPoint: '过氧化钠歧化反应本质、双向电子转移数目计算及极端增重守恒',
    relatedKnowledgeIds: ['sodium', 'redox-reaction'],
    sceneType: 'na-water-cuso4',
  },
  {
    id: 'card-10',
    category: 'inorganic-facts',
    categoryLabel: '无机常识与微粒',
    title: 'Fe(OH)₃ 胶体制备与渗析提纯 vs 过滤分离',
    question: '制备 Fe(OH)₃ 胶体时，正确的操作和胶体提纯分离方法是？',
    optionA: '将饱和 FeCl₃ 滴入沸水中煮沸至红褐色即停；用半透膜渗析提纯除去 Cl⁻',
    optionB: '向沸水中滴加 NaOH 浓溶液；用滤纸过滤除去沉淀',
    correctOption: 'A',
    explanation: '制备：向沸水中逐滴滴加饱和 FeCl₃ 溶液，继续煮沸至液体呈红褐色停止加热，切忌用玻璃棒搅拌或长时间加热（否则聚沉）；胶体粒子能透过滤纸但不能透过半透膜，故用渗析法分离胶体与离子。',
    chemicalEquations: [
      'FeCl_3 + 3H_2O \\xrightarrow{\\Delta} Fe(OH)_3(\\text{胶体}) + 3HCl (饱和溶液滴入沸水煮沸)',
    ],
    warningTip: '高考避坑红线：制备胶体绝对不能加 NaOH（会直接出沉淀），不能用玻璃棒搅拌，不能过度加热！胶体与浊液用过滤分开，胶体与溶液用半透膜分开。',
    examPoint: '胶体制备实验规范、丁达尔效应物理本质与渗析分离净化原理',
    relatedKnowledgeIds: ['iron', 'mixture-separation'],
    sceneType: 'colloid-tyndall',
  },
  {
    id: 'card-11',
    category: 'organic-experiment',
    categoryLabel: '有机机理与实验',
    title: '检验卤代烃中卤素原子加硝酸酸化的必要性',
    question: '检验 1-溴丁烷中溴元素时，水解后加入 AgNO₃ 溶液之前，必须进行的关键操作是？',
    optionA: '必须先加入过量稀硝酸酸化，中和过量的 NaOH',
    optionB: '无需酸化，直接滴加 AgNO₃ 溶液即可',
    correctOption: 'A',
    explanation: '卤代烃水解在强碱性条件下进行，溶液中含有大量 OH⁻。若不加硝酸酸化直接滴入 AgNO₃，OH⁻ 会与 Ag⁺ 反应生成黑褐色的 Ag₂O 沉淀，严重干扰对淡黄色 AgBr 沉淀的判断！',
    chemicalEquations: [
      'CH_3CH_2CH_2CH_2Br + NaOH \\xrightarrow{H_2O, \\Delta} CH_3CH_2CH_2CH_2OH + NaBr (强碱性水解)',
      'H^+ + OH^- = H_2O (加稀硝酸中和过量碱)',
      'Ag^+ + Br^- = AgBr\\downarrow (淡黄色沉淀)',
    ],
    warningTip: '高考避坑红线：未酸化直接加 AgNO₃ 产生棕黑色沉淀是高考常见丢分点！切记必须用“稀硝酸”，不能用盐酸酸化！',
    examPoint: '卤代烃水解实验完整检验链：水解→加稀硝酸酸化→加AgNO₃→观察沉淀颜色',
    relatedKnowledgeIds: ['haloalkane', 'chlorine'],
    sceneType: 'haloalkane-test',
  },
  {
    id: 'card-12',
    category: 'organic-experiment',
    categoryLabel: '有机机理与实验',
    title: '乙醇消去反应 (170℃) 与分子间脱水 (140℃) 温度控制',
    question: '实验室制备乙烯时，温度计水银球的位置以及温度控制的核心要点是什么？',
    optionA: '水银球必须插入反应液液面以下；迅速升温至 170℃，防止 140℃ 生成乙醚副产物',
    optionB: '水银球放在蒸馏烧瓶支管口处；缓慢升温至 140℃',
    correctOption: 'A',
    explanation: '乙醇在浓硫酸催化下，140℃ 发生分子间脱水生成乙醚；170℃ 发生分子内消去脱水生成乙烯。测定反应混合液温度，水银球必须浸入液面以下，且要迅速升温至 170℃ 减少副反应。',
    chemicalEquations: [
      'CH_3CH_2OH \\xrightarrow{\\text{浓}H_2SO_4, 170^\\circ\\text{C}} CH_2=CH_2\\uparrow + H_2O (分子内消去)',
      '2CH_3CH_2OH \\xrightarrow{\\text{浓}H_2SO_4, 140^\\circ\\text{C}} CH_3CH_2OCH_2CH_3 + H_2O (分子间脱水)',
    ],
    warningTip: '高考避坑红线：温度计水银球测反应液温度（浸入液体中）vs 测馏分沸点（位于支管口下沿）必须严格区分！',
    examPoint: '有机反应温度控制对产物选择性的决定性影响与副反应控制',
    relatedKnowledgeIds: ['ethanol', 'alkene'],
    sceneType: 'ethanol-reaction',
  },
  {
    id: 'card-13',
    category: 'organic-experiment',
    categoryLabel: '有机机理与实验',
    title: '乙醇催化氧化条件与叔醇 (无 α-H) 无法氧化',
    question: '伯醇、仲醇、叔醇在铜催化加热条件下，氧化反应规律是？',
    optionA: '伯醇催化氧化为醛，仲醇催化氧化为酮，叔醇因连接羟基的碳上无氢 (无 α-H) 不能催化氧化',
    optionB: '所有醇类均能被催化氧化为羧酸',
    correctOption: 'A',
    explanation: '醇的催化氧化断键机理是：脱去羟基上的氢原子和羟基所在碳原子 (α-C) 上的氢原子形成 C=O 双键。叔醇的 α-C 上没有氢原子，因此不能发生催化氧化。',
    chemicalEquations: [
      '2R\\text{-}CH_2OH + O_2 \\xrightarrow{Cu, \\Delta} 2R\\text{-}CHO + 2H_2O (伯醇氧化为醛)',
      'R_3C\\text{-}OH + O_2 \\xrightarrow{Cu, \\Delta} \\text{不反应 (叔醇无 } \\alpha\\text{-H)}',
    ],
    warningTip: '高考避坑红线：断键机理是脱去“O-H”键与“α-C-H”键！同理，醇消去反应要求邻位碳上有氢 (β-H)。',
    examPoint: '醇催化氧化的机理微观断键模型及异构体反应活性推断',
    relatedKnowledgeIds: ['ethanol', 'aldehyde'],
    sceneType: 'ethanol-reaction',
  },
  {
    id: 'card-14',
    category: 'organic-experiment',
    categoryLabel: '有机机理与实验',
    title: '苯与甲苯对酸性 KMnO₄ 溶液反应与侧链活化',
    question: '苯不能使酸性高锰酸钾溶液褪色，而甲苯能使其褪色生成苯甲酸，这体现了什么结构影响？',
    optionA: '苯环对侧链甲基产生影响，使甲基变得活泼易被氧化',
    optionB: '甲基对苯环产生影响，使苯环容易开环氧化',
    correctOption: 'A',
    explanation: '烷烃本身通常不与酸性高锰酸钾反应，但当甲基连接在苯环上时，由于苯环大π键的吸电子共轭效应，侧链碳氢键被活化，易被强氧化剂氧化为羧基 (-COOH)。注意：直接与苯环相连的碳上必须有氢才能被氧化！',
    chemicalEquations: [
      '5C_6H_5CH_3 + 6MnO_4^- + 18H^+ \\rightarrow 5C_6H_5COOH + 6Mn^{2+} + 14H_2O (苯环活化侧链被氧化)',
    ],
    warningTip: '高考避坑红线：芳香烃基团相互影响包括两面：苯环活化侧链（使甲基易氧化）；侧链活化苯环（邻对位定位效应使苯环易硝化生成TNT）。',
    examPoint: '有机物分子中基团间相互影响的双向性及官能团活化理论',
    relatedKnowledgeIds: ['benzene', 'carboxylic-acid'],
    sceneType: 'ethanol-reaction',
  },
  {
    id: 'card-15',
    category: 'inorganic-facts',
    categoryLabel: '无机常识与微粒',
    title: '阿伏加德罗常数 ($N_{\\text{A}}$) 标况气体状态陷阱对比',
    question: '在标准状况下 (0℃, 101 kPa)，22.4 L 的 SO₃ 或水 (H₂O) 所含的分子数是否为 $N_{\\text{A}}$？',
    optionA: '否，标况下 SO₃ 为固体（或液体），H₂O 为液体，不能使用 22.4 L/mol 气体摩尔体积计算',
    optionB: '是，任何物质在标况下 22.4 L 均含 1 mol 分子',
    correctOption: 'A',
    explanation: '气体摩尔体积 Vm ≈ 22.4 L/mol 仅适用于“标准状况下的气体”！标况下常见非气体：H₂O (液)、SO₃ (固/液，熔点16.8℃)、HF (液)、己烷及碳数大于4的烷烃 (液)、CHCl₃/CCl₄ (液)、乙醇 (液) 等。',
    chemicalEquations: [
      'n = \\frac{V}{V_m} \\quad (V_m = 22.4 \\text{ L/mol 仅适用于标况气体})',
    ],
    warningTip: '高考避坑红线：NA题第一看“状况”（标准状况 vs 常温常压），第二看“状态”（标况下水、SO₃、HF、碳原子数>4的烃类均为非气态）！',
    examPoint: '阿伏加德罗常数全景陷阱、物质状态边界与微粒守恒计算',
    relatedKnowledgeIds: ['gas-molar-volume', 'sulfur'],
    sceneType: 'gas-compress',
  },
  {
    id: 'card-16',
    category: 'experiment-templates',
    categoryLabel: '实验规范答题',
    title: '高考必背模板：沉淀洗涤的标准操作规范',
    question: '在过滤分离实验中，如何规范描述“沉淀洗涤”的操作方法？',
    optionA: '向漏斗中加水并用玻璃棒快速搅拌，直到完全洗净',
    optionB: '沿玻璃棒向漏斗中注入蒸馏水至浸没沉淀，待洗涤液自然流下，重复操作 2~3 次',
    correctOption: 'B',
    explanation: '标准洗涤规范包含三个踩分点：① 沿玻璃棒向漏斗中注入蒸馏水至浸没沉淀；② 静置待洗涤液自然流下；③ 重复操作 2~3 次。绝对禁止使用玻璃棒搅拌，防止戳破滤纸！',
    chemicalEquations: [],
    templateSteps: [
      { step: 1, title: '加液浸没', desc: '沿玻璃棒向漏斗中注入蒸馏水（或指定洗涤液）至浸没沉淀表面' },
      { step: 2, title: '自然流下', desc: '静置，待洗涤液从漏斗下端自然全部流下' },
      { step: 3, title: '重复洗涤', desc: '重复上述操作 2～3 次，直至沉淀彻底洗涤干净' },
    ],
    warningTip: '高考避坑红线：操作描述严禁出现“搅拌”字样！搅拌会戳破滤纸或使沉淀透过滤纸孔隙流失。',
    examPoint: '过滤操作规范、沉淀洗涤三步法踩分点与实验安全规程',
    relatedKnowledgeIds: ['mixture-separation'],
    sceneType: 'colloid-tyndall',
  },
  {
    id: 'card-17',
    category: 'experiment-templates',
    categoryLabel: '实验规范答题',
    title: '高考必背模板：沉淀是否洗净的检验操作与现象',
    question: '以洗涤附着有硫酸钠或氯化钠的沉淀为例，如何规范描述“沉淀是否洗净”的检验操作、现象与结论？',
    optionA: '取最后一次洗涤滤液少量于试管中，加入对应沉淀试剂（如酸化BaCl₂或AgNO₃），若无沉淀生成，证明沉淀已洗净',
    optionB: '取漏斗中的沉淀加入试管中，加入试剂观察是否有气泡',
    correctOption: 'A',
    explanation: '标准踩分三部曲：① 取样：取最后一次洗涤液少许于试管中；② 操作：滴加稀硝酸酸化的 AgNO₃（检验Cl⁻）或滴加稀盐酸酸化的 BaCl₂（检验SO₄²⁻）；③ 现象与结论：若无沉淀生成，证明沉淀已洗净；若产生沉淀，则未洗净。',
    chemicalEquations: [
      'Ag^+ + Cl^- = AgCl\\downarrow (取最后一次洗涤液酸化检验，无沉淀即洗净)',
    ],
    templateSteps: [
      { step: 1, title: '规范取样', desc: '取最后一次洗涤滤液少量于洁净试管中' },
      { step: 2, title: '滴加试剂', desc: '滴加稀硝酸酸化后，再滴入硝酸银溶液（或稀盐酸酸化滴加BaCl₂）' },
      { step: 3, title: '现象结论', desc: '若溶液中无沉淀生成，则证明沉淀已洗涤干净；反之则未洗净' },
    ],
    warningTip: '高考避坑红线：必须明确写出“取最后一次洗涤液”！写“取滤液”或“取漏斗中液体”直接扣除步骤分。',
    examPoint: '沉淀洗涤终点检验的标准句式、排除干扰离子的试剂选择与踩分要点',
    relatedKnowledgeIds: ['mixture-separation', 'chlorine'],
    sceneType: 'colloid-tyndall',
  },
  {
    id: 'card-18',
    category: 'experiment-templates',
    categoryLabel: '实验规范答题',
    title: '高考必背模板：滴定终点判定的标准规范描述',
    question: '在用酸性 KMnO₄ 滴定 Fe²⁺ 溶液时，如何规范描述达到“滴定终点”的现象？',
    optionA: '当滴入最后半滴 KMnO₄ 标准液时，溶液由浅绿色变为浅粉红色，且半分钟内不褪色',
    optionB: '溶液颜色变红就立刻停止滴定并读数',
    correctOption: 'A',
    explanation: '高考滴定终点判定三要素（缺一不可）：① 动作：当滴入最后半滴标准液时；② 变色：溶液由某色变为某色（注明颜色变化方向）；③ 时间：且半分钟（30秒）内不恢复原色，即达到滴定终点。',
    chemicalEquations: [
      '5Fe^{2+} + MnO_4^- + 8H^+ = 5Fe^{3+} + Mn^{2+} + 4H_2O (滴入最后半滴，半分钟内不恢复原色)',
    ],
    templateSteps: [
      { step: 1, title: '关键动作', desc: '当滴入最后半滴标准溶液后' },
      { step: 2, title: '颜色突变', desc: '锥形瓶内溶液由无色（或浅绿色）突变为浅紫红色' },
      { step: 3, title: '时间限定', desc: '且在半分钟（30 秒）内不褪色（或不恢复原色），即达到滴定终点' },
    ],
    warningTip: '高考避坑红线：必须包含“最后半滴”、“由某色变为某色”、“半分钟内不褪色（不恢复原色）”三大采分核心词！',
    examPoint: '酸碱与氧化还原滴定终点标准规范答题术语及误差分析',
    relatedKnowledgeIds: ['redox-reaction', 'iron'],
    sceneType: 'fe-kscn-equilibrium',
  },
  {
    id: 'card-19',
    category: 'experiment-templates',
    categoryLabel: '实验规范答题',
    title: '高考必背模板：带分液漏斗气体制备装置气密性检验',
    question: '对于带有分液漏斗的气体发生装置（如启普发生器变式），采用“微热法”检验气密性的标准步骤是？',
    optionA: '关闭分液漏斗旋塞，导管末端浸入水槽中，微热烧瓶有气泡冒出，移开热源后导管内形成一段稳定水柱',
    optionB: '打开分液漏斗旋塞，向烧瓶内吹气看是否有水流出',
    correctOption: 'A',
    explanation: '标准步骤：① 构筑密闭体系：关闭分液漏斗旋塞，将导气管末端伸入盛水的水槽中；② 微热观察：用手捂热（或酒精灯微热）烧瓶，导管口有气泡冒出；③ 冷却观察：移开双手（或热源），导管内形成一段稳定的水柱，且一段时间内不下降，证明气密性良好。',
    chemicalEquations: [],
    templateSteps: [
      { step: 1, title: '密闭体系', desc: '关闭分液漏斗旋塞，将导气管末端浸入水槽的水面以下' },
      { step: 2, title: '受热膨胀', desc: '双手紧贴（或用酒精灯微热）容器外壁，观察到导管口有连续气泡冒出' },
      { step: 3, title: '冷却倒吸', desc: '移开热源冷却，导气管末端形成一段稳定的水柱，持续一段时间不下降，证明气密性良好' },
    ],
    warningTip: '高考避坑红线：必须说明第一步“关闭分液漏斗旋塞”形成封闭体系，且必须完整回答“微热出气泡”和“冷却形成稳定水柱”两段过程！',
    examPoint: '微热法与液差法气密性检验的物理化学机制与规范表达',
    relatedKnowledgeIds: ['gas-preparation'],
    sceneType: 'gas-compress',
  },
  {
    id: 'card-20',
    category: 'experiment-templates',
    categoryLabel: '实验规范答题',
    title: '高考必背模板：恒压滴液漏斗 (恒压分液漏斗) 的核心作用',
    question: '有机合成或易挥发实验中常使用恒压滴液漏斗，其侧面玻璃连通管的核心作用是什么？',
    optionA: '平衡漏斗上方与烧瓶内的气压，使漏斗中液体能顺利滴下；同时可减小液体挥发或防止有害气体外逸',
    optionB: '增大反应体系压强，加速反应速率',
    correctOption: 'A',
    explanation: '恒压漏斗通过侧管使漏斗上部气相空间与烧瓶内部连通，具有两大作用：① 平衡气压：使烧瓶内气压与漏斗液面上方气压相等，液体在自身重力作用下能顺利滴下；② 密闭防逸：避免打开漏斗塞加液，防止易挥发、易吸水水解或有毒有害气体逸出污染环境。',
    chemicalEquations: [],
    templateSteps: [
      { step: 1, title: '平衡气压', desc: '连通漏斗上方气相与反应容器，平衡体系内部压强' },
      { step: 2, title: '顺利滴下', desc: '消除密闭体系负压或正压阻力，使漏斗中液体顺利滴下' },
      { step: 3, title: '密闭防逸', desc: '全密闭操作，防止易挥发物质逸散或外界水汽进入体系' },
    ],
    warningTip: '高考避坑红线：答题不仅要回答“使液体顺利滴下”，高分必须指出“平衡漏斗上方与烧瓶内部气压”的本质机理！',
    examPoint: '恒压滴液漏斗结构特点、压强平衡原理及仪器选择题眼',
    relatedKnowledgeIds: ['gas-preparation'],
    sceneType: 'passivation-heat',
  },
  {
    id: 'card-21',
    category: 'experiment-templates',
    categoryLabel: '实验规范答题',
    title: '高考必背模板：易溶气体尾气吸收防倒吸原理',
    question: '对于极易溶于水的气体 (如 HCl、NH₃、SO₂)，尾气吸收时采用倒置漏斗或球形干燥管防倒吸的物理原理是？',
    optionA: '当水上升到漏斗/球形部位时，容积增大导致重力增大，水自动脱离液面回落，从而防止液体倒吸进入反应装置',
    optionB: '倒置漏斗能加速气体溶解，使气压降为零',
    correctOption: 'A',
    explanation: '倒置漏斗边缘刚接触液面，一旦由于气体极易溶解导致管内压强骤降，液体倒吸入漏斗中，由于漏斗容积大，水面上升迅速脱离水槽液面，液体在重力作用下又回落到水槽中，从而有效防止倒吸。',
    chemicalEquations: [],
    templateSteps: [
      { step: 1, title: '负压倒吸', desc: '极易溶气体快速溶解引起导管内压强骤降，吸收液迅速倒吸入宽腔中' },
      { step: 2, title: '脱离液面', desc: '宽腔容积大，液体进入后漏斗下沿脱离吸收液液面' },
      { step: 3, title: '重力回落', desc: '吸入的液体在自身重力作用下重新回落到烧杯中，从而有效防止倒吸' },
    ],
    warningTip: '高考避坑红线：倒置漏斗下沿必须【刚接触液面（轻触液面）】，绝对不能深插入液面以下！',
    examPoint: '尾气处理防倒吸装置原理与实验安全',
    relatedKnowledgeIds: ['gas-preparation', 'nitrogen'],
    sceneType: 'gas-compress',
  },
]

export const FLASH_CARD_CATEGORIES = [
  { value: 'all', label: '全部盲盒 (21大易错与规范专题)' },
  { value: 'experiment-templates', label: '高考实验规范答题模板 (必背)' },
  { value: 'bleaching-redox', label: '漂白与氧化对比' },
  { value: 'passivation-acid', label: '钝化与强酸特性' },
  { value: 'equilibrium-color', label: '平衡与加压变色' },
  { value: 'inorganic-facts', label: '无机常识与微粒陷阱' },
  { value: 'organic-experiment', label: '有机机理与实验常识' },
] as const
