import type { FlashCard } from './types'

export const FLASH_CARDS: FlashCard[] = [
  {
    id: 'card-1',
    category: 'bleaching-redox',
    categoryLabel: '漂白与氧化',
    title: 'SO₂ 与 Cl₂ 漂白品红后加热复红对比',
    question: '将 SO₂ 和 Cl₂ 分别通入品红溶液中使其褪色，随后分别加热褪色后的溶液，现象有何不同？',
    optionA: '通入 SO₂ 的溶液加热恢复红色；通入 Cl₂ 的溶液加热不恢复红色',
    optionB: '两者加热后均能完全恢复红色',
    correctOption: 'A',
    explanation: 'SO₂ 漂白属于结合型（与色素生成不稳定无色物质，加热解离复红）；Cl₂ 漂白是因为生成强氧化性的 HClO 破坏色素结构，不可逆且加热不复红。',
    chemicalEquations: [
      'SO_2 + 色素 \\rightleftharpoons 无色物质 (加热逆向解离复红)',
      'Cl_2 + H_2O = HCl + HClO (强氧化破坏色素，加热不复红)',
    ],
    warningTip: '高考避坑红线：区分结合型漂白（SO₂）、氧化型漂白（Cl₂/HClO/O₃/Na₂O₂）与吸附型漂白（活性炭）。仅 SO₂ 漂白加热可复红！',
    examPoint: 'SO₂ 漂白的物理化学可逆性与 Cl₂ 强氧化性不可逆漂白的机理辨析',
    relatedKnowledgeIds: ['sulfur', 'chlorine'],
    sceneType: 'bleach-heating',
  },
  {
    id: 'card-2',
    category: 'bleaching-redox',
    categoryLabel: '漂白与氧化',
    title: '等物质的量 SO₂ 与 Cl₂ 混合通入品红溶液',
    question: '将等物质的量的 SO₂ 与 Cl₂ 混合后通入品红溶液中，溶液是否褪色？',
    optionA: '褪色更迅速，漂白效果叠加增强',
    optionB: '不褪色，两者在水溶液中发生氧化还原反应失去漂白性',
    correctOption: 'B',
    explanation: '等摩尔的 SO₂ 与 Cl₂ 混合通入水中，发生反应 SO₂ + Cl₂ + 2H₂O = H₂SO₄ + 2HCl，生成的硫酸与盐酸无漂白性，故品红溶液不褪色。',
    chemicalEquations: ['SO_2 + Cl_2 + 2H_2O = H_2SO_4 + 2HCl'],
    warningTip: '高考避坑红线：切忌直觉以为“两种漂白剂混合效果加倍”！氧化性与还原性气体混合优先发生氧化还原反应。',
    examPoint: '氧化还原反应竞争优先于性质表现及代数等当量判断',
    relatedKnowledgeIds: ['sulfur', 'chlorine'],
    sceneType: 'bleach-heating',
  },
  {
    id: 'card-3',
    category: 'bleaching-redox',
    categoryLabel: '漂白与氧化',
    title: 'SO₂ 与 CO₂ 使澄清石灰水与高锰酸钾褪色对比',
    question: 'SO₂ 和 CO₂ 通入澄清石灰水均能变浑浊，如何用化学试剂快速鉴别 SO₂ 与 CO₂？',
    optionA: '通入酸性 KMnO₄ 溶液，能使其紫红色褪色的是 SO₂，不能的是 CO₂',
    optionB: '通入品红溶液无现象的是 SO₂',
    correctOption: 'A',
    explanation: 'SO₂ 具有强还原性，能被酸性 KMnO₄ 或溴水氧化使其褪色；而 CO₂ 无还原性不反应。通入澄清石灰水两者均生成不溶性钙盐沉淀。',
    chemicalEquations: [
      '5SO_2 + 2MnO_4^- + 2H_2O = 5SO_4^{2-} + 2Mn^{2+} + 4H^+',
      'SO_2 + Ca(OH)_2 = CaSO_3\\downarrow + H_2O',
    ],
    warningTip: '高考避坑红线：SO₂ 使酸性 KMnO₄ 褪色是还原性（发生了氧化还原反应），而不是漂白性！',
    examPoint: 'SO₂ 的还原性与漂白性的严格区分，以及 CO₂/SO₂ 气体检验顺序链',
    relatedKnowledgeIds: ['sulfur', 'carbon-dioxide'],
    sceneType: 'bleach-heating',
  },
  {
    id: 'card-4',
    category: 'passivation-acid',
    categoryLabel: '钝化与强酸',
    title: '常温下铁/铝在浓硫酸中的钝化现象与本质',
    question: '常温下将铁片投入浓硫酸中无气泡产生，这是因为铁与浓硫酸不发生化学反应吗？',
    optionA: '错，常温发生钝化（表面氧化为致密薄膜），钝化属于化学变化',
    optionB: '对，常温下铁金属性弱无法与浓硫酸反应，加热才能反应',
    correctOption: 'A',
    explanation: '常温下浓硫酸、浓硝酸具有强氧化性，使 Fe、Al 表面立即氧化生成一层致密的钝化氧化膜（如 Fe₃O₄），阻止反应继续进行。钝化是化学变化！',
    chemicalEquations: [
      'Fe / Al + \\text{浓}H_2SO_4 / \\text{浓}HNO_3 \\xrightarrow{\\text{常温}} \\text{致密氧化物薄膜 (钝化阻断反应)}',
      '2Fe + 6H_2SO_4(\\text{浓}) \\xrightarrow{\\Delta} Fe_2(SO_4)_3 + 3SO_2\\uparrow + 6H_2O (加热破膜反应)',
    ],
    warningTip: '高考避坑红线：钝化绝不是“不反应”，而是“剧烈反应生成致密膜后阻断”！可以用铝瓶装运常温浓硝酸。',
    examPoint: '钝化概念解析、物理变化与化学变化界定及加热破膜反应',
    relatedKnowledgeIds: ['iron', 'aluminum', 'sulfur'],
    sceneType: 'passivation-heat',
  },
  {
    id: 'card-5',
    category: 'passivation-acid',
    categoryLabel: '钝化与强酸',
    title: '铜与浓硝酸 vs 稀硝酸反应产物与气体颜色对比',
    question: '铜分别与浓硝酸和稀硝酸反应，产生的气体与溶液颜色有何差异？',
    optionA: '浓硝酸产生红棕色 NO₂ 气体；稀硝酸产生无色 NO 气体（遇空气变红棕色）',
    optionB: '浓硝酸产生无色 NO 气体；稀硝酸产生红棕色 NO₂ 气体',
    correctOption: 'A',
    explanation: 'Cu + 4HNO₃(浓) = Cu(NO₃)₂ + 2NO₂↑ + 2H₂O (红棕色)；3Cu + 8HNO₃(稀) = 3Cu(NO₃)₂ + 2NO↑ + 4H₂O (无色，在空气中被 O₂ 氧化为 NO₂)。浓硝酸反应更剧烈。',
    chemicalEquations: [
      'Cu + 4HNO_3(\\text{浓}) = Cu(NO_3)_2 + 2NO_2\\uparrow + 2H_2O (红棕色)',
      '3Cu + 8HNO_3(\\text{稀}) = 3Cu(NO_3)_2 + 2NO\\uparrow + 4H_2O (无色)',
      '2NO + O_2 = 2NO_2 (无色变红棕色)',
    ],
    warningTip: '高考避坑红线：稀硝酸还原产物为 NO，浓硝酸还原产物为 NO₂。硝酸越稀，氮元素得电子后价态降得越低（如可降至 NH₄⁺）。',
    examPoint: '浓稀硝酸氧化性强弱与电子转移还原产物多样性',
    relatedKnowledgeIds: ['copper', 'nitrogen'],
    sceneType: 'passivation-heat',
  },
  {
    id: 'card-6',
    category: 'equilibrium-color',
    categoryLabel: '平衡与颜色',
    title: 'NO₂ 与 N₂O₄ 平衡体系压缩体积加压变色探究',
    question: '在带活塞的针筒中充有 2NO₂ ⇌ N₂O₄ 混合气体，快速压缩活塞缩小体积，气体颜色如何变化？',
    optionA: '瞬间变深，随后随平衡右移稍变浅，但新平衡颜色仍比压缩前深',
    optionB: '瞬间变浅，随后随平衡左移逐渐变深',
    correctOption: 'A',
    explanation: '缩小体积瞬间，NO₂ 浓度大幅增加致颜色变深；随后压强增大平衡向气体分子数减小的右方移动，c(NO₂) 有所降低使颜色稍变浅，但根据勒夏特列原理，新平衡 c(NO₂) 依然高于压缩前。',
    chemicalEquations: ['2NO_2(g) \\rightleftharpoons N_2O_4(g) \\quad \\Delta H < 0 (加压右移，降温右移)'],
    warningTip: '高考避坑红线：平衡移动只能“减弱”改变，不能“消除”改变！加压后 NO₂ 浓度恒大于加压前。',
    examPoint: '勒夏特列原理在气态平衡压缩/膨胀与颜色变化中的极致考查',
    relatedKnowledgeIds: ['le-chatelier', 'nitrogen'],
    sceneType: 'gas-compress',
  },
  {
    id: 'card-7',
    category: 'equilibrium-color',
    categoryLabel: '平衡与颜色',
    title: 'FeCl₃ 与 KSCN 平衡体系中加入固体 KSCN 颜色变化',
    question: '在 Fe³⁺ + 3SCN⁻ ⇌ Fe(SCN)₃ (血红色) 溶液中加入少许 KSCN 固体，溶液血红色有何变化？',
    optionA: '变深，因为 c(SCN⁻) 增加导致平衡正向移动',
    optionB: '不变，因为固体不影响溶液浓度',
    correctOption: 'A',
    explanation: '加入 KSCN 固体溶解后电离出 SCN⁻，使反应物浓度 c(SCN⁻) 增大，平衡向正反应方向移动，生成更多血红色的 Fe(SCN)₃，故溶液血红色加深。',
    chemicalEquations: ['Fe^{3+} + 3SCN^- \\rightleftharpoons Fe(SCN)_3 (血红色)'],
    warningTip: '高考避坑红线：加入 KSCN 固体使 SCN⁻ 浓度增大部分；若加入 NaOH 固体则生成 Fe(OH)₃ 沉淀使 Fe³⁺ 浓度降低，颜色变浅！',
    examPoint: '溶液中络合平衡与浓度改变对移动方向的影响',
    relatedKnowledgeIds: ['iron', 'le-chatelier'],
    sceneType: 'fe-kscn-equilibrium',
  },
  {
    id: 'card-8',
    category: 'inorganic-facts',
    categoryLabel: '无机常识',
    title: '金属钠投入 CuSO₄ 溶液反应本质与现象',
    question: '将一小块金属钠 (Na) 投入 CuSO₄ 溶液中，能否置换出红色的铜 (Cu) 单质？',
    optionA: '不能，钠先与水剧烈反应生成 NaOH 和 H₂，NaOH 再与 CuSO₄ 生成蓝色 Cu(OH)₂ 沉淀',
    optionB: '能，由于钠的金属性比铜强，直接发生置换反应 2Na + Cu²⁺ = 2Na⁺ + Cu',
    correctOption: 'A',
    explanation: '极活泼金属 (Na, K, Ca) 投入盐溶液中，不能置换出金属单质，而是优先与水剧烈反应生成强碱和 H₂，生成的碱再与盐发生复分解反应。',
    chemicalEquations: [
      '2Na + 2H_2O = 2NaOH + H_2\\uparrow',
      '2NaOH + CuSO_4 = Cu(OH)_2\\downarrow + Na_2SO_4 (蓝色沉淀)',
    ],
    warningTip: '高考避坑红线：Na/K/Ca 绝对不能从水溶液中置换金属！只有在熔融盐（如熔融 TiCl₄）中才能置换出金属。',
    examPoint: '活泼金属与水反应的竞争优先性及置换反应条件限制',
    relatedKnowledgeIds: ['sodium', 'copper'],
    sceneType: 'na-water-cuso4',
  },
  {
    id: 'card-9',
    category: 'inorganic-facts',
    categoryLabel: '无机常识',
    title: 'Na₂O₂ 与 CO₂/H₂O 反应电子转移与固体重增规律',
    question: '1 mol Na₂O₂ 与足量 CO₂ 完全反应时，转移的电子数目与固体质量增加量为？',
    optionA: '转移 1 N_A 电子，固体质量增加相当于 1 mol CO 的质量 (28g)',
    optionB: '转移 2 N_A 电子，固体质量增加相当于 1 mol CO₂ 的质量 (44g)',
    correctOption: 'A',
    explanation: '2Na₂O₂ + 2CO₂ = 2Na₂CO₃ + O₂ 是歧化反应，Na₂O₂ 中 -1 价氧既作氧化剂又作还原剂，1 mol Na₂O₂ 转移 1 mol e⁻。2Na₂O₂ → 2Na₂CO₃ 相当于固体增加了 2 mol CO。',
    chemicalEquations: [
      '2Na_2O_2 + 2CO_2 = 2Na_2CO_3 + O_2 (1mol Na_2O_2 转移 1mol e^-)',
      'Na_2O_2 + CO = Na_2CO_3 (固体重增量等于通入 CO 的质量)',
    ],
    warningTip: '高考避坑红线：Na₂O₂ 与 CO₂/H₂O 反应中，每生成 1 mol O₂ 转移 2 mol 电子，消解 2 mol Na₂O₂！',
    examPoint: '歧化反应电子转移数计算与 Na₂O₂ 差量法质量推算',
    relatedKnowledgeIds: ['sodium', 'avogadro-constant'],
    sceneType: 'na-water-cuso4',
  },
  {
    id: 'card-10',
    category: 'inorganic-facts',
    categoryLabel: '无机常识',
    title: 'Fe(OH)₃ 胶体制备与渗析提纯 vs 过滤分离',
    question: '制备 Fe(OH)₃ 胶体时，正确的操作方法以及胶体与溶液分离提纯的方法是？',
    optionA: '向沸水中滴加饱和 FeCl₃ 溶液至红褐色；用渗析（半透膜）提纯胶体',
    optionB: '向 FeCl₃ 溶液中加入浓 NaOH 溶液；用滤纸过滤分离胶体',
    correctOption: 'A',
    explanation: '制备胶体需将饱和 FeCl₃ 滴入沸水煮沸至红褐色，不能加强碱或搅拌（会导致沉淀/聚沉）；胶体粒子能穿透滤纸但不能穿透半透膜，故渗析用于提纯胶体。',
    chemicalEquations: ['FeCl_3 + 3H_2O \\xrightarrow{\\Delta} Fe(OH)_3(\\text{胶体}) + 3HCl'],
    warningTip: '高考避坑红线：胶体粒子直径介于 1~100 nm，能产生丁达尔效应，能穿透滤纸！滤纸不能分离胶体与溶液！',
    examPoint: '胶体制备细节、丁达尔效应物理本质与渗析半透膜提纯',
    relatedKnowledgeIds: ['iron', 'separation-purification'],
    sceneType: 'colloid-tyndall',
  },
  {
    id: 'card-11',
    category: 'organic-experiment',
    categoryLabel: '有机与实验',
    title: '检验卤代烃中卤素原子加硝酸酸化的必要性',
    question: '检验 1-溴丁烷中的溴元素：NaOH 溶液加热水解后，在加入 AgNO₃ 溶液之前为什么必须加稀 HNO₃？',
    optionA: '中和未反应完的 OH⁻，防止 OH⁻ 与 Ag⁺ 生成棕黑色 Ag₂O 沉淀干扰检验',
    optionB: '催化 AgBr 沉淀迅速生成',
    correctOption: 'A',
    explanation: '水解体系呈强碱性，含过量 OH⁻。如果不加稀 HNO₃ 酸化，Ag⁺ 会优先与 OH⁻ 反应生成棕黑色 Ag₂O 沉淀，掩盖 AgBr 淡黄色沉淀的观察。',
    chemicalEquations: [
      'CH_3CH_2CH_2CH_2Br + NaOH \\xrightarrow{H_2O, \\Delta} CH_3CH_2CH_2CH_2OH + NaBr',
      'OH^- + H^+ = H_2O (HNO_3 酸化)',
      'Ag^+ + Br^- = AgBr\\downarrow (淡黄色沉淀)',
    ],
    warningTip: '高考避坑红线：检验卤代烃或银镜反应后的硝酸洗涤，必须注意体系 pH！强碱性环境必须用稀硝酸中和！',
    examPoint: '有机官能团检验流程细节与离子干扰消除',
    relatedKnowledgeIds: ['halogenated-hydrocarbon'],
    sceneType: 'haloalkane-test',
  },
  {
    id: 'card-12',
    category: 'organic-experiment',
    categoryLabel: '有机与实验',
    title: '乙醇消去反应 (170℃) 与分子间脱水 (140℃) 温度控制',
    question: '实验室用乙醇与浓硫酸制备乙烯时，为何温度必须迅速升至 170℃？',
    optionA: '170℃ 发生分子内消去生成乙烯；140℃ 会发生分子间脱水生成副产物乙醚',
    optionB: '170℃ 浓硫酸氧化性最强',
    correctOption: 'A',
    explanation: 'CH₃CH₂OH 在 170℃ 时在浓硫酸作用下发生分子内消去生成 CH₂=CH₂ 和 H₂O；而在 140℃ 时则主要发生分子间脱水生成 CH₃CH₂OCH₂CH₃ (乙醚)。',
    chemicalEquations: [
      'CH_3CH_2OH \\xrightarrow{\\text{浓}H_2SO_4, 170^\\circ\\text{C}} CH_2=CH_2\\uparrow + H_2O (分子内消去)',
      '2CH_3CH_2OH \\xrightarrow{\\text{浓}H_2SO_4, 140^\\circ\\text{C}} CH_3CH_2OCH_2CH_3 + H_2O (分子间脱水)',
    ],
    warningTip: '高考避坑红线：温度计水银球必须浸入反应液液面以下！反应易产生 SO₂ 和 CO₂ 杂质气体（需用 NaOH 洗气）。',
    examPoint: '温度对副反应方向的决定性控制与乙烯制备实验安全规范',
    relatedKnowledgeIds: ['ethylene', 'carboxylic-acid-ester'],
    sceneType: 'ethanol-reaction',
  },
  {
    id: 'card-13',
    category: 'organic-experiment',
    categoryLabel: '有机与实验',
    title: '乙醇催化氧化条件与叔醇 (无 α-H) 无法氧化',
    question: '醇发生催化氧化 (Cu/Ag 催化) 生成醛或酮的结构前提条件是什么？叔丁醇能否被催化氧化？',
    optionA: '相连 -OH 的碳原子 (α-C) 上必须有 H 原子；叔丁醇 α-C 上无 H 无法被催化氧化',
    optionB: '只要含有 -OH 羟基即可被催化氧化',
    correctOption: 'A',
    explanation: '醇催化氧化本质是脱去 -OH 上的 H 和 α-C 上的 H。R-CH₂OH 氧化为醛，R₂CHOH 氧化为酮；而 R₃COH (叔醇) 的 α-C 上无 H，常温催化无法被氧化。',
    chemicalEquations: [
      '2R-CH_2OH + O_2 \\xrightarrow{Cu, \\Delta} 2R-CHO + 2H_2O (伯醇变醛)',
      'R_3C-OH + O_2 \\xrightarrow{Cu, \\Delta} \\text{无反应 (叔醇无 } \\alpha-H)',
    ],
    warningTip: '高考避坑红线：醇催化氧化反应中铜网加热变黑 (CuO)，插入乙醇中又变红 (Cu)，铜作催化剂！',
    examPoint: '官能团位置与 α-H 对反应可行性的机理决定作用',
    relatedKnowledgeIds: ['carboxylic-acid-ester'],
    sceneType: 'ethanol-reaction',
  },
  {
    id: 'card-14',
    category: 'organic-experiment',
    categoryLabel: '有机与实验',
    title: '苯与甲苯对酸性 KMnO₄ 溶液反应与侧链活化',
    question: '苯和甲苯分别加入酸性 KMnO₄ 溶液中震荡，现象有何不同？说明了什么？',
    optionA: '苯不反应（上层无色下层紫红/萃取分层）；甲苯使紫红色褪去；说明苯环活化了甲基侧链',
    optionB: '两者均能使酸性 KMnO₄ 溶液褪色',
    correctOption: 'A',
    explanation: '苯环非常稳定，不能被酸性 KMnO₄ 氧化；而甲苯中苯环受侧链影响活化了甲基 (α-C 上有 H)，甲基被氧化为 -COOH (苯甲酸)。这体现了“苯环对侧链的影响”。',
    chemicalEquations: ['C_6H_5-CH_3 + KMnO_4(H^+) \\rightarrow C_6H_5-COOH (甲苯变苯甲酸)'],
    warningTip: '高考避坑红线：与苯环相连的 α-C 上必须含有 H 才能被酸性 KMnO₄ 氧化为 -COOH！若为 C₆H₅-C(CH₃)₃ 则不能褪色！',
    examPoint: '有机物基团相互影响理论与酸性 KMnO₄ 氧化规律',
    relatedKnowledgeIds: ['isomerism'],
    sceneType: 'ethanol-reaction',
  },
  {
    id: 'card-15',
    category: 'inorganic-facts',
    categoryLabel: '无机常识',
    title: '阿伏加德罗常数 (N_A) 标况气体状态陷阱对比',
    question: '标准状况 (0℃, 101 kPa) 下，22.4 L SO₃ 和 22.4 L CCl₄ 中含有的分子数目是否为 N_A？',
    optionA: '否，标况下 SO₃ 为固体，CCl₄ 为液体，不能使用 22.4 L/mol 气体摩尔体积计算',
    optionB: '是，任意气体或物质在标况下 22.4 L 均含有 N_A 个分子',
    correctOption: 'A',
    explanation: '气体摩尔体积 $V_m = 22.4\\text{ L/mol}$ 仅适用于**标准状况下的气体**。标况下 SO₃ 为固态 (熔点 16.8℃)，CCl₄、H₂O、HF、辛烷等为液态，不能用 22.4 L/mol 计算！',
    chemicalEquations: ['n = \\frac{V}{V_m} \\quad (V_m = 22.4 \\text{ L/mol } \\text{仅适用于标况气体})'],
    warningTip: '高考避坑红线：高频标况非气体陷阱：SO₃ (固/液)、CCl₄ (液)、H₂O (液/固)、HF (液)、己烷/苯 (液)。逢 22.4 L 必先看状态！',
    examPoint: '阿伏加德罗常数选择题选项精准避坑考查',
    relatedKnowledgeIds: ['avogadro-constant', 'gas-molar-volume'],
    sceneType: 'gas-compress',
  },
]

export const FLASH_CARD_CATEGORIES = [
  { value: 'all', label: '全部分类 (15大易错盲盒)' },
  { value: 'bleaching-redox', label: '漂白与氧化对比' },
  { value: 'passivation-acid', label: '钝化与强酸特性' },
  { value: 'equilibrium-color', label: '平衡与加压变色' },
  { value: 'inorganic-facts', label: '无机常识与微粒陷阱' },
  { value: 'organic-experiment', label: '有机机理与实验常识' },
] as const
